/**
 * Typed Snowplow tracking wrappers — STUB.
 *
 * ─── Why hand-written (Snowtype fallback) ────────────────────────────────────
 * In a finished demo these wrappers are GENERATED by Snowtype from your data
 * products. When a Console API key isn't available non-interactively, hand-write
 * thin, typed wrappers that call `trackSelfDescribingEvent` with the exact PROD
 * Iglu URIs. If a Console API key is later provided, run
 * `npx @snowplow/snowtype init` + `generate` and swap the callsites over to the
 * generated `trackX()` functions — keep the event/entity shapes matching 1:1.
 *
 * CONVENTION: funnel EVERY custom tracking call in the app through this module.
 *
 * This stub ships only the login event (used by the identity-stitch in
 * user-context.tsx) and one example self-describing event. Replace `com.demo`
 * with your vendor and add your demo's events/entities here.
 */

import { trackSelfDescribingEvent } from '@snowplow/browser-tracker';
import type { SelfDescribingJson } from '@snowplow/browser-tracker';

// ─── Iglu URIs (replace vendor + add your schemas) ────────────────────────────

const SCHEMAS = {
  login: 'iglu:com.demo/login/jsonschema/1-0-0',
  // Example custom event — delete or replace.
  contentInteraction: 'iglu:com.demo/content_interaction/jsonschema/1-0-0',
} as const;

// ─── Types ────────────────────────────────────────────────────────────────────

export type LoginMethod = 'email' | 'google' | 'facebook' | 'apple';
export type LoginStatus = 'success' | 'failure';

export type ContentInteractionType = 'add_to_library' | 'share' | 'favorite';

// ─── Event wrappers ─────────────────────────────────────────────────────────

/**
 * Login.
 * NOTE: the anonymous→known identity stitch (setUserId + disable anonymous
 * tracking) is performed by the CALLER before this fires — see user-context.tsx.
 */
export function trackLogin(params: {
  login_method?: LoginMethod | null;
  login_status?: LoginStatus | null;
  failure_reason?: string | null;
}): void {
  trackSelfDescribingEvent({
    event: {
      schema: SCHEMAS.login,
      data: {
        login_method: params.login_method ?? null,
        login_status: params.login_status ?? null,
        failure_reason: params.failure_reason ?? null,
      },
    },
  });
}

/**
 * Example custom event carrying an arbitrary entity as context. Copy this shape
 * for your demo's events; attach entities via the `context` array.
 */
export function trackContentInteraction(
  type: ContentInteractionType,
  context: SelfDescribingJson[] = []
): void {
  trackSelfDescribingEvent({
    event: { schema: SCHEMAS.contentInteraction, data: { type } },
    context,
  });
}
